global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - "alerts/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

scrape_configs:
  - job_name: 'fastapi-payment-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']
